# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true

mainSections = ["docs"]
# robots = ""

# Disables image zoom feature across all the images in the site.
disableImageZoom = true

disableImageOptimization = true

defaultBackgroundImage = "/img/matterhorn.jpeg"

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/matterhorn.jpeg" # used in: hero, and card
  showRecent = false
  showRecentItems = 10
  showMoreLink = false
  showMoreLinkDest = "docs"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editURL = "https://github.com/bitcoin-alps/website/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = false
  sharingLinks = []

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false


[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
    
[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
